### ISSUE TITLE
Fazer uma query depois da migração para deixar o status dos registros sem status como concluído

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/gembib#126]
Verificar o que fazer com os que ainda não tem tombo...

**Comment by gabrielareisg** [comment]
pelo o que eu vi, os que não tem tombo geralmente são os que estão com o status "Negado" ou "Sugestão", mas tem exceções

**Comment by gabrielareisg** [comment]
9910 tombos que possuem o título "N�O INFORMADO"

**Comment by thiagogomesverissimo** [comment]
"Remendos":

    UPDATE itens SET status="Processado"  where status ='';
    UPDATE itens SET titulo ='NÃO INFORMADO'  where titulo ='N�O INFORMADO';
